player_names = {
    "precious achiuwa": ["precious achiuwa", "achiuwa", "precious"],
    "steven adams": ["steven adams", "adams"],
    "bam adebayo": ["bam adebayo", "adebayo", " bam", "bam "],
    "santi aldama": ["santi aldama", "aldama"],
    "lamarcus aldridge": ["lamarcus aldridge", "aldridge"],
    "nickeil alexander-walker": ["nickeil alexander-walker", "alexander-walker", "nickeil alexander walker", "alexander walker", "nickeil"],
    "grayson allen": ["grayson allen", "grayson"],
    "jarrett allen": ["jarrett allen", "jarrett"],
    "jose alvarado": ["jose alvarado", "alvarado"],
    "justin anderson": ["justin anderson"],
    "kyle anderson": ["kyle anderson", "anderson"],
    "giannis antetokounmpo": ["giannis antetokounmpo", "antetokounmpo", "giannis"],
    "thanasis antetokounmpo": ["thanasis antetokounmpo", "thanasis"],
    "carmelo anthony": ["carmelo anthony", "carmelo"],
    "cole anthony": ["cole anthony"],
    "og anunoby": ["og anunoby", "anunoby", " og "],
    "ryan arcidiacono": ["ryan arcidiacono", "arcidiacono"],
    "trevor ariza": ["trevor ariza", "ariza"],
    "d.j. augustin": ["d.j. augustin", "augustin", "dj augustin"],
    "deni avdija": ["deni avdija", "avdija", " deni "],
    "joel ayayi": ["joel ayayi", "ayayi"],
    "deandre ayton": ["deandre ayton", " ayton"],
    "udoka azubuike": ["udoka azubuike", "azubuike"],
    "marvin bagley iii": ["marvin bagley iii", "bagley"],
    "lamelo ball": ["lamelo ball", "lamelo"],
    "lonzo ball": ["lonzo ball", "lonzo"],
    "mo bamba": ["mo bamba", "bamba"],
    "desmond bane": ["desmond bane", "bane"],
    "dalano banton": ["dalano banton", "banton"],
    "cat barber": ["cat barber", "barber"],
    "harrison barnes": ["harrison barnes"],
    "scottie barnes": ["scottie barnes", "scottie", "barnes"],
    "rj barrett": ["rj barrett", "barrett", "rj ", " rj"],
    "will barton": ["will barton", "barton"],
    "paris bass": ["paris bass", " bass "],
    "charles bassey": ["charles bassey", "bassey"],
    "keita bates-diop": ["keita bates-diop", "bates-diop"],
    "nicolas batum": ["nicolas batum", "batum"],
    "kent bazemore": ["kent bazemore", "bazemore"],
    "darius bazley": ["darius bazley", "bazley"],
    "bradley beal": ["bradley beal", "beal"],
    "malik beasley": ["malik beasley", "beasley"],
    "jordan bell": ["jordan bell"],
    "deandre bembry": ["deandre bembry", "bembry"],
    "davis bertans": ["davis bertans", "bertans"],
    "patrick beverley": ["patrick beverley", "beverley"],
    "saddiq bey": ["saddiq bey", "saddiq"],
    "khem birch": ["khem birch", "birch"],
    "goga bitadze": ["goga bitadze", "bitadze"],
    "bismack biyombo": ["bismack biyombo", "biyombo", "bismack"],
    "nemanja bjelica": ["nemanja bjelica", "bjelica"],
    "eric bledsoe": ["eric bledsoe", "bledsoe"],
    "keljin blevins": ["keljin blevins", "blevins"],
    "bogdan bogdanovic": ["bogdan bogdanovic", "bogdanovic", "bogdan"],
    "bojan bogdanovic": ["bojan bogdanovic", "bogdanovic", "bojan"],
    "bol bol": ["bol bol", " bol "],
    "leandro bolmaro": ["leandro bolmaro", "bolmaro"],
    "isaac bonga": ["isaac bonga", "bonga"],
    "devin booker": ["devin booker", "booker", "dbook"],
    "brandon boston jr.": ["brandon boston jr", "brandon boston"],
    "chris boucher": ["chris boucher", "boucher"],
    "james bouknight": ["james bouknight", "bouknight"],
    "avery bradley": ["avery bradley", "avery"],
    "tony bradley": ["tony bradley"],
    "ignas brazdeikis": ["ignas brazdeikis", "brazdeikis", "ignas"],
    "mikal bridges": ["mikal bridges", "mikal"],
    "miles bridges": ["miles bridges", "bridges"],
    "oshae brissett": ["oshae brissett", "brissett"],
    "malcolm brogdon": ["malcolm brogdon", "brogdon"],
    "armoni brooks": ["armoni brooks", "armoni"],
    "dillon brooks": ["dillon brooks", " brooks"],
    "bruce brown": ["bruce brown"],
    "charlie brown jr.": ["charlie brown jr", "charlie brown"],
    "chaundee brown jr.": ["chaundee brown jr", "chaundee brown"],
    "greg brown iii": ["greg brown iii", "greg brown"],
    "jaylen brown": ["jaylen brown"],
    "moses brown": ["moses brown"],
    "sterling brown": ["sterling brown"],
    "troy brown jr.": ["troy brown jr", "troy brown"],
    "jalen brunson": ["jalen brunson", "brunson"],
    "thomas bryant": ["thomas bryant"],
    "shaq buchanan": ["shaq buchanan", "buchanan"],
    "reggie bullock": ["reggie bullock", "bullock"],
    "trey burke": ["trey burke", "burke"],
    "alec burks": ["alec burks", "burks"],
    "jared butler": ["jared butler"],
    "jimmy butler": ["jimmy butler", "butler", "jimmy"],
    "devontae cacok": ["devontae cacok", "cacok"],
    "kentavious caldwell-pope": ["kentavious caldwell-pope", "caldwell-pope", "kentavious caldwell pope", "caldwell pope", "kcp", "kentavious"],
    "facundo campazzo": ["facundo campazzo", "campazzo"],
    "vlatko cancar": ["vlatko cancar", "cancar"],
    "devin cannady": ["devin cannady", "cannady"],
    "clint capela": ["clint capela", "capela"],
    "vernon carey jr.": ["vernon carey jr", "vernon carey"],
    "jevon carter": ["jevon carter"],
    "wendell carter jr.": ["wendell carter jr", "wendell carter"],
    "alex caruso": ["alex caruso", "caruso"],
    "willie cauley-stein": ["willie cauley-stein", "cauley-stein", "willie cauley stein", "cauley stein"],
    "ahmad caver": ["ahmad caver", "caver"],
    "justin champagnie": ["justin champagnie", "champagnie"],
    "zylan cheatham": ["zylan cheatham", "cheatham"],
    "chris chiozza": ["chris chiozza", "chiozza"],
    "marquese chriss": ["marquese chriss", "chriss"],
    "josh christopher": ["josh christopher"],
    "gary clark": ["gary clark"],
    "brandon clarke": ["brandon clarke", "clarke"],
    "jordan clarkson": ["jordan clarkson", "clarkson"],
    "nic claxton": ["nic claxton", "claxton"],
    "amir coffey": ["amir coffey", "coffey"],
    "john collins": ["john collins", "collins"],
    "zach collins": ["zach collins"],
    "darren collison": ["darren collison", "collison"],
    "mike conley": ["mike conley", "conley"],
    "pat connaughton": ["pat connaughton", "connaughton"],
    "tyler cook": ["tyler cook"],
    "sharife cooper": ["sharife cooper", "cooper"],
    "petr cornelie": ["petr cornelie", "cornelie"],
    "demarcus cousins": ["demarcus cousins", "cousins", "demarcus", "boogie"],
    "robert covington": ["robert covington", "covington"],
    "torrey craig": ["torrey craig"],
    "jae crowder": ["jae crowder", "crowder"],
    "jarrett culver": ["jarrett culver", "culver"],
    "jarron cumberland": ["jarron cumberland", "cumberland"],
    "cade cunningham": ["cade cunningham", "cunningham"],
    "seth curry": ["seth curry", "seth"],
    "stephen curry": ["stephen curry", "curry", "steph "],
    "anthony davis": ["anthony davis", " ad "],
    "ed davis": ["ed davis"],
    "terence davis": ["terence davis"],
    "javin delaurier": ["javin delaurier", "delaurier"],
    "demar derozan": ["demar derozan", "derozan"],
    "gabriel deck": ["gabriel deck"],
    "dewayne dedmon": ["dewayne dedmon", "dedmon"],
    "sam dekker": ["sam dekker", "dekker"],
    "donte divincenzo": ["donte divincenzo", "divincenzo"],
    "mamadi diakite": ["mamadi diakite", "diakite"],
    "cheick diallo": ["cheick diallo"],
    "hamidou diallo": ["hamidou diallo", "diallo"],
    "gorgui dieng": ["gorgui dieng", "dieng"],
    "spencer dinwiddie": ["spencer dinwiddie", "dinwiddie"],
    "luka doncic": ["luka doncic", "doncic", "luka"],
    "luguentz dort": ["luguentz dort", "dort ", "luguentz"],
    "ayo dosunmu": ["ayo dosunmu", "dosunmu"],
    "damyean dotson": ["damyean dotson"],
    "devon dotson": ["devon dotson", "dotson"],
    "sekou doumbouya": ["sekou doumbouya", "doumbouya", "sekou"],
    "jeff dowtin": ["jeff dowtin", "dowtin"],
    "pj dozier": ["pj dozier", "dozier"],
    "goran dragic": ["goran dragic", "dragic", "goran"],
    "andre drummond": ["andre drummond", "drummond"],
    "chris duarte": ["chris duarte", "duarte"],
    "david duke jr.": ["david duke jr", "david duke"],
    "kris dunn": ["kris dunn", "dunn "],
    "kevin durant": ["kevin durant", "durant", "kd ", " kd"],
    "jaime echenique": ["jaime echenique", "echenique"],
    "anthony edwards": ["anthony edwards", "edwards", " ant "],
    "carsen edwards": ["carsen edwards"],
    "kessler edwards": ["kessler edwards"],
    "rob edwards": ["rob edwards"],
    "cj elleby": ["cj elleby", "elleby"],
    "wayne ellington": ["wayne ellington", "ellington"],
    "joel embiid": ["joel embiid", "embiid", "joel"],
    "james ennis iii": ["james ennis iii", "james ennis"],
    "drew eubanks": ["drew eubanks", "eubanks"],
    "tacko fall": ["tacko fall", "tacko"],
    "derrick favors": ["derrick favors", "favors"],
    "bruno fernando": ["bruno fernando", "fernando"],
    "dorian finney-smith": ["dorian finney-smith", "finney-smith", "dorian finney smith", "finney smith"],
    "malik fitts": ["malik fitts", "fitts"],
    "malachi flynn": ["malachi flynn", "flynn"],
    "bryn forbes": ["bryn forbes", "forbes"],
    "aleem ford": ["aleem ford"],
    "trent forrest": ["trent forrest", "forrest"],
    "evan fournier": ["evan fournier", "fournier"],
    "de'aaron fox": ["de'aaron fox", "de'aaron", "deaaron fox", " deaaron", "de aaron fox", "de aaron"],
    "melvin frazier": ["melvin frazier"],
    "tim frazier": ["tim frazier", "frazier"],
    "enes freedom": ["enes freedom", "kanter", "enes kanter"],
    "markelle fultz": ["markelle fultz", "fultz", "markelle"],
    "wenyen gabriel": ["wenyen gabriel", "wenyen"],
    "daniel gafford": ["daniel gafford", "gafford"],
    "danilo gallinari": ["danilo gallinari", "gallinari", "danilo"],
    "langston galloway": ["langston galloway", "galloway", "langston"],
    "darius garland": ["darius garland", "garland"],
    "marcus garrett": ["marcus garrett", "garrett"],
    "usman garuba": ["usman garuba", "garuba"],
    "luka garza": ["luka garza", "garza"],
    "rudy gay": ["rudy gay"],
    "paul george": ["paul george", "pg13"],
    "taj gibson": ["taj gibson", "gibson", "taj"],
    "josh giddey": ["josh giddey", "giddey"],
    "shai gilgeous-alexander": ["shai gilgeous-alexander", "gilgeous-alexander", "shai gilgeous alexander", "gilgeous alexander", "shai"],
    "anthony gill": ["anthony gill"],
    "freddie gillespie": ["freddie gillespie", "gillespie"],
    "rudy gobert": ["rudy gobert", "gobert"],
    "brandon goodwin": ["brandon goodwin", "goodwin"],
    "jordan goodwin": ["jordan goodwin"],
    "aaron gordon": ["aaron gordon"],
    "eric gordon": ["eric gordon"],
    "devonte graham": ["devonte graham", "graham"],
    "jerami grant": ["jerami grant", "jerami"],
    "hassani gravett": ["hassani gravett", "gravett"],
    "danny green": ["danny green"],
    "draymond green": ["draymond green", "draymond", "dray"],
    "jalen green": ["jalen green"],
    "jamychal green": ["jamychal green"],
    "javonte green": ["javonte green"],
    "jeff green": ["jeff green"],
    "josh green": ["josh green"],
    "blake griffin": ["blake griffin", "griffin", "blake"],
    "quentin grimes": ["quentin grimes", "grimes"],
    "kyle guy": ["kyle guy"],
    "rui hachimura": ["rui hachimura", "hachimura", "rui ",],
    "tyrese haliburton": ["tyrese haliburton", "haliburton"],
    "tyler hall": ["tyler hall" ],
    "r.j. hampton": ["r.j. hampton", "hampton"],
    "tim hardaway jr.": ["tim hardaway jr", "tim hardaway", "hardaway"],
    "james harden": ["james harden", "harden"],
    "maurice harkless": ["maurice harkless", "harkless"],
    "jared harper": ["jared harper", "harper"],
    "montrezl harrell": ["montrezl harrell", "harrell", "montrezl"],
    "gary harris": ["gary harris"],
    "joe harris": ["joe harris"],
    "tobias harris": ["tobias harris", "tobias"],
    "shaquille harrison": ["shaquille harrison"],
    "josh hart": ["josh hart"],
    "isaiah hartenstein": ["isaiah hartenstein", "hartenstein"],
    "udonis haslem": ["udonis haslem", "haslem", "udonis"],
    "sam hauser": ["sam hauser", "hauser"],
    "jaxson hayes": ["jaxson hayes", "hayes"],
    "killian hayes": ["killian hayes"],
    "gordon hayward": ["gordon hayward", "hayward"],
    "aaron henry": ["aaron henry", "henry"],
    "juancho hernangomez": ["juancho hernangomez", "hernangomez"],
    "willy hernangomez": ["willy hernangomez"],
    "tyler herro": ["tyler herro", "herro"],
    "buddy hield": ["buddy hield", "hield"],
    "haywood highsmith": ["haywood highsmith", "highsmith"],
    "george hill": ["george hill"],
    "malcolm hill": ["malcolm hill"],
    "solomon hill": ["solomon hill"],
    "nate hinton": ["nate hinton", "hinton"],
    "jaylen hoard": ["jaylen hoard", "hoard"],
    "aaron holiday": ["aaron holiday"],
    "jrue holiday": ["jrue holiday", "jrue"],
    "justin holiday": ["justin holiday"],
    "richaun holmes": ["richaun holmes", "holmes"],
    "rodney hood": ["rodney hood"],
    "scotty hopson": ["scotty hopson", "hopson"],
    "al horford": ["al horford", "horford"],
    "talen horton-tucker": ["talen horton-tucker", "horton-tucker", "talen horton tucker", "horton tucker"],
    "danuel house jr.": ["danuel house jr", "danuel house"],
    "dwight howard": ["dwight howard", "howard"],
    "markus howard": ["markus howard"],
    "kevin huerter": ["kevin huerter", "huerter"],
    "jay huff": ["jay huff"],
    "elijah hughes": ["elijah hughes", "hughes"],
    "feron hunt": ["feron hunt"],
    "de'andre hunter": ["de'andre hunter", "hunter", "deandre hunter", "de andre hunter", "de andre", "deandre"],
    "chandler hutchison": ["chandler hutchison", "hutchison"],
    "bones hyland": ["bones hyland", "hyland"],
    "serge ibaka": ["serge ibaka", "ibaka", "serge"],
    "andre iguodala": ["andre iguodala", "iguodala", " iggy "],
    "joe ingles": ["joe ingles", "ingles ", " ingles"],
    "brandon ingram": ["brandon ingram", "ingram"],
    "kyrie irving": ["kyrie irving", "irving", "kyrie"],
    "jonathan isaac": ["jonathan isaac"],
    "wes iwundu": ["wes iwundu", "iwundu"],
    "frank jackson": ["frank jackson"],
    "isaiah jackson": ["isaiah jackson"],
    "jaren jackson jr.": ["jaren jackson jr", "jaren jackson"],
    "josh jackson": ["josh jackson"],
    "justin jackson": ["justin jackson"],
    "reggie jackson": ["reggie jackson"],
    "lebron james": ["lebron james", "lebron", "bron ", "lbj"],
    "dejon jarreau": ["dejon jarreau", "jarreau"],
    "daquan jeffries": ["daquan jeffries", "jeffries"],
    "ty jerome": ["ty jerome", "jerome"],
    "isaiah joe": ["isaiah joe"],
    "alize johnson": ["alize johnson"],
    "b.j. johnson": ["b.j. johnson"],
    "cameron johnson": ["cameron johnson", "cam johnson"],
    "david johnson": ["david johnson"],
    "jalen johnson": ["jalen johnson"],
    "james johnson": ["james johnson"],
    "joe johnson": ["joe johnson"],
    "keldon johnson": ["keldon johnson"],
    "keon johnson": ["keon johnson"],
    "stanley johnson": ["stanley johnson"],
    "tyler johnson": ["tyler johnson"],
    "nikola jokic": ["nikola jokic", "jokic", "joker"],
    "carlik jones": ["carlik jones"],
    "damian jones": ["damian jones"],
    "derrick jones jr.": ["derrick jones jr", "derrick jones"],
    "herbert jones": ["herbert jones"],
    "jemerrio jones": ["jemerrio jones"],
    "kai jones": ["kai jones"],
    "mason jones": ["mason jones"],
    "tre jones": ["tre jones"],
    "tyus jones": ["tyus jones", "tyus"],
    "deandre jordan": ["deandre jordan"],
    "cory joseph": ["cory joseph", "joseph"],
    "georgios kalaitzakis": ["georgios kalaitzakis", "kalaitzakis"],
    "frank kaminsky": ["frank kaminsky", "kaminsky"],
    "luke kennard": ["luke kennard", "kennard"],
    "braxton key": ["braxton key"],
    "george king": ["george king"],
    "louis king": ["louis king"],
    "corey kispert": ["corey kispert", "kispert"],
    "maxi kleber": ["maxi kleber", "kleber"],
    "brandon knight": ["brandon knight", " knight "],
    "nathan knight": ["nathan knight"],
    "kevin knox": ["kevin knox", "knox"],
    "john konchar": ["john konchar", "konchar"],
    "furkan korkmaz": ["furkan korkmaz", "korkmaz"],
    "luke kornet": ["luke kornet", "kornet"],
    "vit krejci": ["vit krejci", "krejci"],
    "arnoldas kulboka": ["arnoldas kulboka", "kulboka"],
    "jonathan kuminga": ["jonathan kuminga", "kuminga"],
    "kyle kuzma": ["kyle kuzma", "kuzma", "kuz", "kyle kuz"],
    "zach lavine": ["zach lavine", "lavine"],
    "anthony lamb": ["anthony lamb"],
    "jeremy lamb": ["jeremy lamb", "lamb"],
    "jock landale": ["jock landale", "landale"],
    "romeo langford": ["romeo langford", "langford"],
    "jake layman": ["jake layman", "layman"],
    "caris levert": ["caris levert", "levert", "caris"],
    "damion lee": ["damion lee"],
    "saben lee": ["saben lee"],
    "alex len": ["alex len", " len "],
    "kawhi leonard": ["kawhi leonard", "leonard"],
    "meyers leonard": ["meyers leonard", "leonard"],
    "kira lewis jr.": ["kira lewis jr", "kira lewis"],
    "scottie lewis": ["scottie lewis"],
    "damian lillard": ["damian lillard", "lillard", "dame lillard", "dame"],
    "nassir little": ["nassir little", "nassir"],
    "isaiah livers": ["isaiah livers", "livers"],
    "kevon looney": ["kevon looney", "looney", "kevon"],
    "brook lopez": ["brook lopez"],
    "robin lopez": ["robin lopez"],
    "didi louzada": ["didi louzada", "louzada"],
    "kevin love": ["kevin love"],
    "kyle lowry": ["kyle lowry", "lowry"],
    "gabriel lundberg": ["gabriel lundberg", "lundberg"],
    "timothe luwawu-cabarrot": ["timothe luwawu-cabarrot", "luwawu-cabarrot", "timothe luwawu cabarrot", "luwawu cabarrot"],
    "trey lyles": ["trey lyles", "lyles"],
    "thon maker": ["thon maker", " maker"],
    "theo maledon": ["theo maledon", "maledon"],
    "sandro mamukelashvili": ["sandro mamukelashvili", "mamukelashvili"],
    "nico mannion": ["nico mannion", "mannion"],
    "terance mann": ["terance mann"],
    "tre mann": ["tre mann", "mann "],
    "boban marjanovic": ["boban marjanovic", "marjanovic"],
    "lauri markkanen": ["lauri markkanen", "markkanen"],
    "naji marshall": ["naji marshall", "marshall", "naji"],
    "caleb martin": ["caleb martin"],
    "cody martin": ["cody martin"],
    "kelan martin": ["kelan martin"],
    "kenyon martin jr.": ["kenyon martin jr", "kenyon martin"],
    "garrison mathews": ["garrison mathews", "mathews"],
    "dakota mathias": ["dakota mathias", "mathias"],
    "wesley matthews": ["wesley matthews", "matthews"],
    "tyrese maxey": ["tyrese maxey", "maxey"],
    "skylar mays": ["skylar mays", "mays"],
    "miles mcbride": ["miles mcbride", "mcbride"],
    "mac mcclung": ["mac mcclung", "mcclung"],
    "cj mccollum": ["cj mccollum", "mccollum"],
    "t.j. mcconnell": ["t.j. mcconnell", "mcconnell", "tj mcconnell"],
    "jaden mcdaniels": ["jaden mcdaniels", "mcdaniels"],
    "jalen mcdaniels": ["jalen mcdaniels"],
    "doug mcdermott": ["doug mcdermott", "mcdermott"],
    "javale mcgee": ["javale mcgee", "mcgee", "javale"],
    "cameron mcgriff": ["cameron mcgriff", "mcgriff", "cam mcgriff"],
    "rodney mcgruder": ["rodney mcgruder", "mcgruder"],
    "alfonzo mckinnie": ["alfonzo mckinnie", "mckinnie"],
    "jaquori mclaughlin": ["jaquori mclaughlin"],
    "jordan mclaughlin": ["jordan mclaughlin", "mclaughlin"],
    "ben mclemore": ["ben mclemore", "mclemore"],
    "de'anthony melton": ["de'anthony melton", "melton", "deanthony melton"],
    "sam merrill": ["sam merrill", "merrill"],
    "chimezie metu": ["chimezie metu", "metu"],
    "khris middleton": ["khris middleton", "middleton", "khris"],
    "c.j. miles": ["c.j. miles", "cj miles"],
    "patty mills": ["patty mills"],
    "paul millsap": ["paul millsap", "millsap"],
    "shake milton": ["shake milton", " milton"],
    "davion mitchell": ["davion mitchell"],
    "donovan mitchell": ["donovan mitchell", "donovan"],
    "evan mobley": ["evan mobley", "mobley"],
    "malik monk": ["malik monk", " monk "],
    "greg monroe": ["greg monroe", "monroe"],
    "moses moody": ["moses moody", "moody"],
    "xavier moon": ["xavier moon"],
    "matt mooney": ["matt mooney", "mooney"],
    "ja morant": ["ja morant", "morant", "ja "],
    "juwan morgan": ["juwan morgan", "morgan", "juwan"],
    "jaylen morris": ["jaylen morris"],
    "marcus morris": ["marcus morris", "morris"],
    "markieff morris": ["markieff morris", "morris", "markieff"],
    "monte morris": ["monte morris"],
    "emmanuel mudiay": ["emmanuel mudiay", "mudiay"],
    "mychal mulder": ["mychal mulder", "mulder"],
    "ade murkey": ["ade murkey", "murkey"],
    "trey murphy iii": ["trey murphy iii", "trey murphy"],
    "dejounte murray": ["dejounte murray", "dejounte"],
    "jamal murray": ["jamal murray", "murray"],
    "mike muscala": ["mike muscala", "muscala"],
    "svi mykhailiuk": ["svi mykhailiuk", "mykhailiuk"],
    "abdel nader": ["abdel nader", "nader"],
    "larry nance jr.": ["larry nance jr", "larry nance"],
    "rj nembhard jr.": ["rj nembhard jr", "rj nembhard"],
    "aaron nesmith": ["aaron nesmith", "nesmith"],
    "raul neto": ["raul neto", "neto"],
    "malik newman": ["malik newman", "newman"],
    "georges niang": ["georges niang", "niang"],
    "daishen nix": ["daishen nix", " nix "],
    "zeke nnaji": ["zeke nnaji", "nnaji"],
    "nerlens noel": ["nerlens noel", "noel"],
    "jaylen nowell": ["jaylen nowell", "nowell"],
    "frank ntilikina": ["frank ntilikina", "ntilikina"],
    "jusuf nurkic": ["jusuf nurkic", "nurkic", "jusuf", "nurk"],
    "david nwaba": ["david nwaba", "nwaba"],
    "jordan nwora": ["jordan nwora", "nwora"],
    "royce o'neale": ["royce o'neale", "o'neale", "royce oneale", "oneale", "royce o neale", "o neale"],
    "semi ojeleye": ["semi ojeleye", "ojeleye"],
    "chuma okeke": ["chuma okeke", "okeke"],
    "josh okogie": ["josh okogie", "okogie"],
    "onyeka okongwu": ["onyeka okongwu", "okongwu"],
    "isaac okoro": ["isaac okoro", "okoro"],
    "kz okpala": ["kz okpala", "okpala"],
    "victor oladipo": ["victor oladipo", "oladipo"],
    "cameron oliver": ["cameron oliver", "oliver", "cam oliver"],
    "kelly olynyk": ["kelly olynyk", "olynyk"],
    "eugene omoruyi": ["eugene omoruyi", "omoruyi"],
    "miye oni": ["miye oni"],
    "cedi osman": ["cedi osman", "osman"],
    "daniel oturu": ["daniel oturu", "oturu"],
    "kelly oubre jr.": ["kelly oubre jr", "kelly oubre", "oubre"],
    "jaysean paige": ["jaysean paige", "paige"],
    "trayvon palmer": ["trayvon palmer", "palmer"],
    "kevin pangos": ["kevin pangos", "pangos"],
    "jabari parker": ["jabari parker", "jabari"],
    "eric paschall": ["eric paschall", "paschall"],
    "chris paul": ["chris paul", "cp3" , " cp "],
    "cameron payne": ["cameron payne", "payne", "cam payne"],
    "elfrid payton": ["elfrid payton", "elfrid"],
    "gary payton ii": ["gary payton ii", "gary payton"],
    "norvel pelle": ["norvel pelle"],
    "reggie perry": ["reggie perry", "perry"],
    "jamorko pickett": ["jamorko pickett", "pickett"],
    "theo pinson": ["theo pinson", "pinson"],
    "mason plumlee": ["mason plumlee", "plumlee"],
    "jakob poeltl": ["jakob poeltl", "poeltl"],
    "aleksej pokusevski": ["aleksej pokusevski", "pokusevski"],
    "yves pons": ["yves pons", " pons"],
    "jordan poole": ["jordan poole", "poole"],
    "kevin porter jr.": ["kevin porter jr", "kevin porter"],
    "michael porter jr.": ["michael porter jr", "michael porter"],
    "otto porter jr.": ["otto porter jr", "otto porter", " otto"],
    "bobby portis": ["bobby portis", "portis", "bobby"],
    "kristaps porzingis": ["kristaps porzingis", "porzingis", "kristaps"],
    "micah potter": ["micah potter"],
    "dwight powell": ["dwight powell"],
    "myles powell": ["myles powell"],
    "norman powell": ["norman powell", "norm powell"],
    "joshua primo": ["joshua primo", "josh primo"],
    "taurean prince": ["taurean prince"],
    "payton pritchard": ["payton pritchard", "pritchard"],
    "trevelin queen": ["trevelin queen"],
    "neemias queta": ["neemias queta", "queta"],
    "immanuel quickley": ["immanuel quickley", "quickley"],
    "jahmius ramsey": ["jahmius ramsey", "ramsey"],
    "julius randle": ["julius randle", "randle"],
    "austin reaves": ["austin reaves", "reaves"],
    "cam reddish": ["cam reddish", "reddish"],
    "davon reed": ["davon reed"],
    "paul reed": ["paul reed"],
    "naz reid": ["naz reid", "reid"],
    "nick richards": ["nick richards"],
    "josh richardson": ["josh richardson", "richardson"],
    "austin rivers": ["austin rivers", " rivers", "rivers "],
    "duncan robinson": ["duncan robinson"],
    "justin robinson": ["justin robinson"],
    "mitchell robinson": ["mitchell robinson"],
    "jeremiah robinson-earl": ["jeremiah robinson-earl", "robinson-earl", "jeremiah robinson earl", "robinson earl"],
    "isaiah roby": ["isaiah roby", "roby"],
    "rajon rondo": ["rajon rondo", "rondo"],
    "derrick rose": ["derrick rose", " rose "],
    "terrence ross": ["terrence ross", " ross "],
    "terry rozier": ["terry rozier", "rozier"],
    "ricky rubio": ["ricky rubio", "rubio"],
    "d'angelo russell": ["d'angelo russell", "dangelo russell", "d angelo russell",],
    "matt ryan": ["matt ryan"],
    "domantas sabonis": ["domantas sabonis", "sabonis"],
    "dario saric": ["dario saric", "saric"],
    "olivier sarr": ["olivier sarr", "sarr"],
    "tomas satoransky": ["tomas satoransky", "satoransky"],
    "jordan schakel": ["jordan schakel", "schakel"],
    "admiral schofield": ["admiral schofield", "schofield"],
    "dennis schroder": ["dennis schroder", "schroder"],
    "tre scott": ["tre scott"],
    "jay scrubb": ["jay scrubb", "scrubb"],
    "wayne selden": ["wayne selden", "selden"],
    "alperen sengun": ["alperen sengun", "sengun"],
    "collin sexton": ["collin sexton", "sexton"],
    "landry shamet": ["landry shamet", "shamet"],
    "dayron sharpe": ["dayron sharpe", "sharpe"],
    "pascal siakam": ["pascal siakam", "siakam", "pascal", "spicy p"],
    "chris silva": ["chris silva", "silva"],
    "ben simmons": ["ben simmons", "simmons"],
    "marko simonovic": ["marko simonovic", "simonovic"],
    "anfernee simons": ["anfernee simons", "simons", "anfernee"],
    "zavier simpson": ["zavier simpson", "simpson"],
    "jericho sims": ["jericho sims", "sims"],
    "deividas sirvydis": ["deividas sirvydis", "sirvydis"],
    "javonte smart": ["javonte smart"],
    "marcus smart": ["marcus smart"],
    "dennis smith jr.": ["dennis smith jr", "dennis smith"],
    "ish smith": ["ish smith", " ish "],
    "jalen smith": ["jalen smith"],
    "xavier sneed": ["xavier sneed", "sneed"],
    "tony snell": ["tony snell", "snell"],
    "jaden springer": ["jaden springer", "springer"],
    "cassius stanley": ["cassius stanley", "stanley"],
    "nik stauskas": ["nik stauskas", "stauskas"],
    "lance stephenson": ["lance stephenson", "stephenson"],
    "lamar stevens": ["lamar stevens"],
    "isaiah stewart": ["isaiah stewart", "stewart"],
    "max strus": ["max strus", "strus"],
    "jalen suggs": ["jalen suggs", "suggs"],
    "craig sword": ["craig sword"],
    "keifer sykes": ["keifer sykes", "sykes"],
    "jaesean tate": ["jaesean tate"],
    "jayson tatum": ["jayson tatum", "tatum"],
    "terry taylor": ["terry taylor", "taylor"],
    "garrett temple": ["garrett temple", " temple "],
    "emanuel terry": ["emanuel terry"],
    "tyrell terry": ["tyrell terry"],
    "jon teske": ["jon teske", "teske"],
    "daniel theis": ["daniel theis", "theis"],
    "brodric thomas": ["brodric thomas"],
    "cam thomas": ["cam thomas"],
    "isaiah thomas": ["isaiah thomas"],
    "matt thomas": ["matt thomas"],
    "klay thompson": ["klay thompson", "klay"],
    "tristan thompson": ["tristan thompson", "tristan"],
    "jt thor": ["jt thor", " thor "],
    "matisse thybulle": ["matisse thybulle", "thybulle", "matisse"],
    "killian tillie": ["killian tillie", "tillie"],
    "xavier tillman sr.": ["xavier tillman sr", "xavier tillman", "tillman"],
    "isaiah todd": ["isaiah todd", "todd"],
    "obi toppin": ["obi toppin", "toppin ", "obi "],
    "juan toscano-anderson": ["juan toscano-anderson", "toscano-anderson", "juan toscano anderson", "toscano anderson"],
    "karl-anthony towns": ["karl-anthony towns", "karl anthony towns", "towns", " kat "],
    "gary trent jr.": ["gary trent jr", "gary trent"],
    "p.j. tucker": ["p.j. tucker", "pj tucker", "tucker"],
    "rayjon tucker": ["rayjon tucker"],
    "myles turner": ["myles turner", "turner"],
    "jonas valanciunas": ["jonas valanciunas", "valanciunas", "jonas", "jv"],
    "denzel valentine": ["denzel valentine", "valentine"],
    "fred vanvleet": ["fred vanvleet", "vanvleet", "freddy", "fvv"],
    "jarred vanderbilt": ["jarred vanderbilt", "vanderbilt"],
    "devin vassell": ["devin vassell", "vassell"],
    "gabe vincent": ["gabe vincent", "vincent"],
    "nikola vucevic": ["nikola vucevic", "vucevic"],
    "dean wade": ["dean wade"],
    "franz wagner": ["franz wagner", "franz"],
    "moritz wagner": ["moritz wagner", "moritz", "mo wagner"],
    "ish wainright": ["ish wainright", "wainright"],
    "kemba walker": ["kemba walker", "kemba"],
    "lonnie walker iv": ["lonnie walker iv", "lonnie walker"],
    "m.j. walker": ["m.j. walker", "mj walker"],
    "john wall": ["john wall", "wall "],
    "tyrone wallace": ["tyrone wallace", "wallace"],
    "derrick walton": ["derrick walton", "walton"],
    "brad wanamaker": ["brad wanamaker", "wanamaker"],
    "t.j. warren": ["t.j. warren", "warren", "tj warren"],
    "duane washington jr.": ["duane washington jr", "duane washington"],
    "p.j. washington": ["p.j. washington","pj washington"],
    "yuta watanabe": ["yuta watanabe", "watanabe"],
    "lindy waters iii": ["lindy waters iii", "lindy waters"],
    "tremont waters": ["tremont waters"],
    "trendon watford": ["trendon watford", "watford"],
    "paul watson": ["paul watson", "watson"],
    "quinndary weatherspoon": ["quinndary weatherspoon", "weatherspoon"],
    "russell westbrook": ["russell westbrook", "westbrook", " russ ", "westbrick"],
    "coby white": ["coby white"],
    "derrick white": ["derrick white"],
    "hassan whiteside": ["hassan whiteside", "whiteside"],
    "joe wieskamp": ["joe wieskamp", "wieskamp"],
    "aaron wiggins": ["aaron wiggins"],
    "andrew wiggins": ["andrew wiggins", "wiggins"],
    "lindell wigginton": ["lindell wigginton", "wigginton"],
    "brandon williams": ["brandon williams"],
    "grant williams": ["grant williams"],
    "kenrich williams": ["kenrich williams"],
    "lou williams": ["lou williams", "lou will", "louwill"],
    "patrick williams": ["patrick williams"],
    "robert williams": ["robert williams"],
    "ziaire williams": ["ziaire williams"],
    "zion williamson": ["zion williamson", "williamson", "zion"],
    "d.j. wilson": ["d.j. wilson", "dj wilson"],
    "dylan windler": ["dylan windler", "windler"],
    "justise winslow": ["justise winslow", "winslow"],
    "cassius winston": ["cassius winston", "winston"],
    "james wiseman": ["james wiseman", "wiseman"],
    "christian wood": ["christian wood", " wood "],
    "robert woodard ii": ["robert woodard ii", "robert woodard"],
    "delon wright": ["delon wright", "delon ", " delon"],
    "mckinley wright iv": ["mckinley wright iv", "mckinley wright"],
    "moses wright": ["moses wright"],
    "gabe york": ["gabe york"],
    "thaddeus young": ["thaddeus young", "thaddeus"],
    "trae young": ["trae young", "trae"],
    "omer yurtseven": ["omer yurtseven", "yurtseven"],
    "cody zeller": ["cody zeller", "zeller"],
    "ivica zubac": ["ivica zubac", "zubac"]
}
